version: "3.8"
services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8081
    image: webapp-frontend
    mem_reservation: 10m
    mem_limit: 20m
    ports:
      - "127.0.0.1:8080:80"

  api:
    depends_on:
      - db
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://webapp:secret@db:5432/db
    image: webapp-backend
    mem_reservation: 100m
    mem_limit: 200m
    ports:
      - "127.0.0.1:8081:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: db
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: secret
    mem_reservation: 100m
    mem_limit: 200m
    ports:
      - "127.0.0.1:5432:5432"
